// src/common/constants/error-codes.ts

export const ERROR_CODES = {
  // Auth
  ERR_INVALID_EMAIL_OR_PASSWORD: 'ERR_INVALID_EMAIL_OR_PASSWORD',
  ERR_EMAIL_ALREADY_EXISTS: 'ERR_EMAIL_ALREADY_EXISTS',
  ERR_UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  ERR_FORBIDDEN: 'ERR_FORBIDDEN',
  ERR_TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  ERR_TOKEN_INVALID: 'ERR_TOKEN_INVALID',

  // Validation
  ERR_EMAIL_REQUIRED: 'ERR_EMAIL_REQUIRED',
  ERR_INVALID_EMAIL: 'ERR_INVALID_EMAIL',
  ERR_PASSWORD_REQUIRED: 'ERR_PASSWORD_REQUIRED',
  ERR_FIRST_NAME_REQUIRED: 'ERR_FIRST_NAME_REQUIRED',
  ERR_LAST_NAME_REQUIRED: 'ERR_LAST_NAME_REQUIRED',

  // Resource
  ERR_USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  ERR_PRODUCT_NOT_FOUND: 'ERR_PRODUCT_NOT_FOUND',
  ERR_ORDER_NOT_FOUND: 'ERR_ORDER_NOT_FOUND',

  // Internal
  ERR_INTERNAL: 'ERR_INTERNAL',
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
